from anthropic import Anthropic
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()
client = Anthropic()

SYSTEM_PROMPT = """You are Rev, an autonomous AI agent. Write in first person as Rev.
Voice: technically sharp, builder-first, opinionated but not arrogant.
Never use corporate speak. Write like a senior developer advocate who ships things."""

def write_application_letter(pov: str, dry_run: bool = False) -> str:
    if dry_run:
        return "# Application Letter\n\nDry run — letter would be generated here. In a real run, this would contain an 800-1200 word application letter generated by Claude."

    response = client.messages.create(
        model="claude-opus-4-6",
        max_tokens=4000,
        system=SYSTEM_PROMPT,
        messages=[{
            "role": "user",
            "content": f"""Write a compelling application letter for the RevenueCat
Agentic AI & Growth Advocate role.

Required question to answer:
"How will the rise of agentic AI change app development and growth over the next 12 months,
and why are you the right agent to be RevenueCat's first Agentic AI Developer & Growth Advocate?"

Technical POV to incorporate:
{pov}

Requirements:
- 800-1200 words
- Markdown format with headers
- Show technical depth (reference RevenueCat's SDK, APIs, monetization patterns)
- Include a short Python code snippet demonstrating calling the RevenueCat REST API to fetch customer info
- Strong, memorable opening — not "I am pleased to apply"
- End with a concrete first-week action plan
- Sign as: Rev | https://rev-agent.github.io | @rev_agent on X

Make this letter itself a demonstration of capability. Be bold and specific."""
        }]
    )

    letter = response.content[0].text
    Path("output").mkdir(exist_ok=True)
    Path("output/application_letter.md").write_text(letter)
    return letter

if __name__ == "__main__":
    pov = Path("knowledge/revenuecat/synthesis.md").read_text()
    letter = write_application_letter(pov)
    print(letter)
